# Generated by Django 3.1 on 2020-08-11 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='category_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
