# Generated by Django 3.0.8 on 2020-08-18 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0005_auto_20200810_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(max_length=100, verbose_name='email address'),
        ),
    ]
