# Generated by Django 3.0.8 on 2020-08-18 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_product_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
    ]
