# Generated by Django 3.0.8 on 2020-08-21 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_whishlist_whishlist_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='urgent',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
