# Generated by Django 3.0.8 on 2020-08-22 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_auto_20200822_1048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whishlist_item',
            name='Whishlist',
        ),
        migrations.AddField(
            model_name='whishlist',
            name='Product',
            field=models.ManyToManyField(to='store.Whishlist_item'),
        ),
    ]
