# Generated by Django 3.0.8 on 2020-08-22 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_auto_20200822_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='whishlist_item',
            name='complete',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
