# Generated by Django 3.0.8 on 2020-08-22 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_whishlist_item_complete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whishlist',
            name='Product',
        ),
        migrations.RemoveField(
            model_name='whishlist_item',
            name='complete',
        ),
        migrations.AddField(
            model_name='whishlist_item',
            name='Whishlist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.Whishlist'),
        ),
        migrations.AlterField(
            model_name='whishlist',
            name='Customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.Customer'),
        ),
        migrations.AlterField(
            model_name='whishlist_item',
            name='Product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.Product'),
        ),
    ]
