# Generated by Django 3.0.8 on 2020-08-22 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_whishlist_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='whishlist',
            old_name='Customer',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='whishlist',
            old_name='Product',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='whishlist_item',
            old_name='Product',
            new_name='product',
        ),
    ]
